insert into portfolio_users (email, password, name) VALUES ('carylee@gmail.com', '7be01a57f18b040a75e8de566d93352ba050a1b7e0c49f6b6114ea10b3520dea', 'Cary Lee');
insert into portfolio_users (email, password, name) VALUES ('mcgough.david@gmail.com', '7e988f9fc6241cebf0e9376a558d558d5893befacb3e2c1fbf087bc5ae7a9f06', 'david');
insert into portfolio_users (email, password, name) VALUES ('tepeacock@gmail.com', 'peacockpreston', 'Todd Peacock-Preston');
insert into portfolio_users (email, password, name) VALUES ('admin@localhost.com', 'mypasswd', 'Some Administrator');
insert into portfolio_users (email, password, name) VALUES ('clarkefreak@gmail.com', 'istbnt2tb2nw', 'Nathan Ritter');
insert into portfolio_portfolios (id, name, description, owner) VALUES (portfolio_ids.nextval, 'Practice', 'description', 'carylee@gmail.com');
insert into portfolio_portfolios (id, name, description, owner) VALUES (portfolio_ids.nextval, 'Actual', 'The stocks I actually own', 'carylee@gmail.com');
insert into portfolio_portfolios (id, name, description, owner) VALUES (portfolio_ids.nextval, 'Marshmallows', 'Non-fat, high sugar', 'mcgough.david@gmail.com');
insert into portfolio_portfolios (id, name, description, owner) VALUES (portfolio_ids.nextval, 'Relish', 'Gross, but makes it good', 'mcgough.david@gmail.com');
insert into portfolio_portfolios (id, name, description, owner) VALUES (portfolio_ids.nextval, 'Yummy', 'Yep.', 'mcgough.david@gmail.com');
insert into portfolio_stocks (symbol, shares, cost_basis, holder) VALUES ('SBUX', '100', '28.01', (SELECT id FROM portfolio_portfolios WHERE name='Practice' and owner='carylee@gmail.com'));
insert into portfolio_stocks (symbol, shares, cost_basis, holder) VALUES ('MSFT', '200', '142.58', (SELECT id FROM portfolio_portfolios WHERE name='Practice' and owner='carylee@gmail.com'));
insert into portfolio_stocks (symbol, shares, cost_basis, holder) VALUES ('F', '100', '28.01', (SELECT id FROM portfolio_portfolios WHERE name='Actual' and owner='carylee@gmail.com'));
insert into portfolio_stocks (symbol, shares, cost_basis, holder) VALUES ('CSCO', '200', '142.58', (SELECT id FROM portfolio_portfolios WHERE name='Actual' and owner='carylee@gmail.com'));
insert into portfolio_stocks (symbol, shares, cost_basis, holder) VALUES ('K', '200', '142.58', (SELECT id FROM portfolio_portfolios WHERE name='Actual' and owner='carylee@gmail.com'));
insert into portfolio_stocks (symbol, shares, cost_basis, holder) VALUES ('LUV', '100', '28.01', (SELECT id FROM portfolio_portfolios WHERE name='Marshmallows' and owner='mcgough.david@gmail.com'));
insert into portfolio_stocks (symbol, shares, cost_basis, holder) VALUES ('F', '200', '142.58', (SELECT id FROM portfolio_portfolios WHERE name='Marshmallows' and owner='mcgough.david@gmail.com'));
insert into portfolio_stocks (symbol, shares, cost_basis, holder) VALUES ('K', '200', '142.58', (SELECT id FROM portfolio_portfolios WHERE name='Relish' and owner='mcgough.david@gmail.com'));
insert into portfolio_stocks (symbol, shares, cost_basis, holder) VALUES ('CSCO', '200', '142.58', (SELECT id FROM portfolio_portfolios WHERE name='Relish' and owner='mcgough.david@gmail.com'));

quit;
